# Site settings
url: "https://maths.fan"
title: "Simon L. Rydin Myerson"
tagline: "Personal page"
description: "Publications and links"
author:
  name: Simon Myerson
  alternateName:
    - Simon Rydin Myerson
    - Simon Leo Rydin Myerson
  url: "https://twitter.com/SimonMyerson"
  givenName: Simon
  additionalName: Leo
  familyName:
    - Rydin
    - Myerson
  twitter: SimonMyerson
twitter:
  card: summary
  username: MathsFan
social:
  name: Simon Myerson
  links:
    - https://twitter.com/SimonMyerson
    - https://warwick.ac.uk/fac/sci/maths/people/staff/myerson
locale: en_GB

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Simon L. Rydin Myerson"
resume_title:                   "Leverhulme Early Career Fellow and Warwick Zeeman Lecturer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "simon.rydin-myerson@warwick.ac.uk"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
resume_contact_address:         "Mathematics Institute, Zeeman Building, University of Warwick, Coventry CV4 7AL"

resume_header_contact_info:     "<span itemprop='knowsAbout'>Number Theory</span> • <span itemprop='knowsAbout'>Mathematics</span> • <span itemprop='worksFor'>University&nbsp;of&nbsp;Warwick</span></p>
    <p> Office&nbsp;B2.19 • Zeeman&nbsp;Building  • Coventry&nbsp;CV4&nbsp;7AL • simon.rydin-myerson [at] warwick.ac.uk • he/him/his or they/them/theirs • Please call me Simon"
display_header_contact_info:    "true"

resume_header_intro: "<p>I study the solutions to equations and inequalities in whole numbers. These are called Diophantine problems and they’re part of number theory. I use “analytic” arguments which are often fairly elementary, which makes it analytic number theory.</p>
<p>I’ve become interested in something which seems very different: nonlinear dispersive partial differential equations (nonlinear dispersive PDEs). This is a type of mathematical model which describes physical systems from ocean waves to fibre optic cables.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# This is what I want:
# Publications (? based on projects)
# Graduate supervision (? based on links)
# resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_cv_url:                "https://www.dropbox.com/s/0fbpufvc9mkew73/cv.pdf?raw=1"
  resume_cv_tooltip:            "CV"
  resume_funding_url:           "https://warwick.ac.uk/research/supporting-talent/fellowships/sci-fellowships/ecr/simon-myerson"
  resume_funding_tooltip:       "Fellowship project"
  resume_work_url:              "https://warwick.ac.uk/fac/sci/maths/people/staff/myerson"
  resume_work_tooltip:          "My Warwick webpage"
  resume_name_url:              "https://www.name-coach.com/simon-rydinmyerson"
  resume_name_tooltip:          "Hear my name"
  resume_arXiv_url:             "https://arxiv.org/a/myerson_s_1"
  resume_arXiv_tooltip:         "arXiv"
  resume_publications_url:      "https://wrap.warwick.ac.uk/view/author_id/381400.html"
  resume_publications_tooltip:  "Publications (accepted)"
  resume_phone_url:             "https://peoplesearch.warwick.ac.uk/profile/1972891"
  resume_phone_tooltip:         "Phone (for Warwick users)"
  resume_ORCID_url:             "https://orcid.org/0000-0002-1486-6054"
  resume_ORCID_id:              "ORCID:0000-0002-1486-6054"
  resume_ORCID_tooltip:         "ORCID iD"
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
